name: Trigger auto deployment for container-app-77hkeqe36m36u

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-77hkeqe36m36u-AutoDeployTrigger-c1abd9ea-8bc5-4b94-8b49-0f20f02dfb29.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP77HKEQE36M36U_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP77HKEQE36M36U_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP77HKEQE36M36U_AZURE_SUBSCRIPTION_ID }}

      - name: Clone azure-cli-extensions repo
        uses: actions/checkout@v3
        with:
           repository: snehapar9/test
           path: azure-cli-extensions

      - name: Install latest azure-cli-extensions wheel
        run: az extension add --source '${{github.workspace}}/azure-cli-extensions/containerapp-0.3.50-py2.py3-none-any.whl' --yes

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@e4732da4ecc1c55b1ab37bd88c7d4abbbee674a6
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP77HKEQE36M36U_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP77HKEQE36M36U_REGISTRY_PASSWORD }}
          containerAppName: container-app-77hkeqe36m36u
          resourceGroup: expresstestacaprobesb446
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


